# Generated by Django 4.0.4 on 2022-04-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('drogsNumber', models.IntegerField(max_length=32)),
                ('devicesNumber', models.IntegerField(max_length=32)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='devices_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('devicesProvideNumber', models.IntegerField(max_length=16)),
                ('devicesQuality', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='drogs_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('drogsProvideNumber', models.IntegerField(max_length=16)),
                ('drogsQuality', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='insurance_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('insuranceProvideNumber', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('age', models.IntegerField(max_length=16)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='patient_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dexcribe', models.CharField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.patient')),
            ],
        ),
        migrations.CreateModel(
            name='insurance_provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.IntegerField(max_length=16)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.insurance_company')),
            ],
        ),
        migrations.CreateModel(
            name='drogs_provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.IntegerField(max_length=16)),
                ('devices_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.devices_company')),
            ],
        ),
        migrations.CreateModel(
            name='drogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department')),
            ],
        ),
        migrations.CreateModel(
            name='devicecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department')),
            ],
        ),
    ]
