# Generated by Django 4.0.4 on 2022-04-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_department_devices_company_drogs_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='devicesNumber',
            field=models.IntegerField(verbose_name='医疗设备数量'),
        ),
        migrations.AlterField(
            model_name='department',
            name='drogsNumber',
            field=models.IntegerField(verbose_name='药物数量'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.hospital', verbose_name='所属医院'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='科室名称'),
        ),
        migrations.AlterField(
            model_name='devicecs',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='devicecs',
            name='name',
            field=models.CharField(max_length=32, verbose_name='医疗设备名称'),
        ),
        migrations.AlterField(
            model_name='devices_company',
            name='devicesProvideNumber',
            field=models.IntegerField(verbose_name='提供设备数量'),
        ),
        migrations.AlterField(
            model_name='devices_company',
            name='devicesQuality',
            field=models.IntegerField(verbose_name='设备质量'),
        ),
        migrations.AlterField(
            model_name='devices_company',
            name='name',
            field=models.CharField(max_length=32, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='devices_company',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='drogs',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='drogs',
            name='name',
            field=models.CharField(max_length=32, verbose_name='药品名称'),
        ),
        migrations.AlterField(
            model_name='drogs_company',
            name='drogsProvideNumber',
            field=models.IntegerField(verbose_name='提供药品数量'),
        ),
        migrations.AlterField(
            model_name='drogs_company',
            name='drogsQuality',
            field=models.IntegerField(verbose_name='药品质量'),
        ),
        migrations.AlterField(
            model_name='drogs_company',
            name='name',
            field=models.CharField(max_length=32, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='drogs_company',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='drogs_provide',
            name='amount',
            field=models.IntegerField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='drogs_provide',
            name='devices_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.devices_company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='drogs_provide',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='departmentNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='科室数量'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=32, verbose_name='医院名称'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=64, verbose_name='医院密码'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.CharField(max_length=32, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='insurance_company',
            name='insuranceProvideNumber',
            field=models.IntegerField(verbose_name='提供保险数量'),
        ),
        migrations.AlterField(
            model_name='insurance_company',
            name='name',
            field=models.CharField(max_length=32, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='insurance_company',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='insurance_provide',
            name='amount',
            field=models.IntegerField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='insurance_provide',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.insurance_company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='insurance_provide',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.hospital', verbose_name='所属医院'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='dexcribe',
            field=models.CharField(max_length=64, verbose_name='病例描述'),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.patient', verbose_name='所属患者'),
        ),
    ]
