# Generated by Django 4.0.4 on 2022-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_remove_drogs_provide_devices_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='patientNumber',
            field=models.IntegerField(default=0, verbose_name='科室患者数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.SmallIntegerField(choices=[(12, '黑龙江'), (20, '宁夏'), (4, '福建'), (28, '天津'), (26, '四川'), (10, '河北'), (13, '湖北'), (7, '广西'), (16, '江苏'), (3, '重庆'), (24, '陕西'), (11, '河南'), (23, '山西'), (31, '云南'), (1, '安徽'), (17, '江西'), (22, '山东'), (19, '内蒙古'), (21, '青海'), (25, '上海'), (2, '北京'), (5, '甘肃'), (32, '浙江'), (33, '香港'), (30, '新疆'), (8, '贵州'), (18, '辽宁'), (15, '吉林'), (29, '西藏'), (6, '广东'), (9, '海南'), (34, '澳门'), (27, '台湾'), (14, '湖南')], verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.SmallIntegerField(choices=[(2, '保险公司'), (5, '管理员'), (4, '医疗设备供应商'), (1, '医院'), (3, '医药供应商')], max_length=32, verbose_name='用户种类'),
        ),
    ]
