# Generated by Django 4.0.4 on 2022-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_department_patientnumber_alter_hospital_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.SmallIntegerField(choices=[(20, '宁夏'), (22, '山东'), (3, '重庆'), (28, '天津'), (25, '上海'), (18, '辽宁'), (5, '甘肃'), (14, '湖南'), (9, '海南'), (27, '台湾'), (8, '贵州'), (7, '广西'), (2, '北京'), (15, '吉林'), (1, '安徽'), (4, '福建'), (26, '四川'), (24, '陕西'), (16, '江苏'), (34, '澳门'), (32, '浙江'), (6, '广东'), (10, '河北'), (31, '云南'), (29, '西藏'), (30, '新疆'), (33, '香港'), (19, '内蒙古'), (12, '黑龙江'), (21, '青海'), (17, '江西'), (11, '河南'), (13, '湖北'), (23, '山西')], verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.SmallIntegerField(choices=[(4, '医疗设备供应商'), (1, '医院'), (3, '医药供应商'), (5, '管理员'), (2, '保险公司')], max_length=32, verbose_name='用户种类'),
        ),
    ]
