# Generated by Django 4.0.4 on 2022-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_alter_hospital_province_alter_userinfo_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=32, verbose_name='保险公司名称')),
                ('hospital_name', models.CharField(max_length=32, verbose_name='医院名称')),
                ('score', models.IntegerField(verbose_name='评估分数')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.SmallIntegerField(choices=[(33, '香港'), (19, '内蒙古'), (23, '山西'), (11, '河南'), (10, '河北'), (12, '黑龙江'), (17, '江西'), (24, '陕西'), (9, '海南'), (18, '辽宁'), (22, '山东'), (2, '北京'), (28, '天津'), (25, '上海'), (34, '澳门'), (32, '浙江'), (7, '广西'), (31, '云南'), (6, '广东'), (27, '台湾'), (29, '西藏'), (20, '宁夏'), (21, '青海'), (16, '江苏'), (14, '湖南'), (8, '贵州'), (5, '甘肃'), (1, '安徽'), (13, '湖北'), (3, '重庆'), (26, '四川'), (4, '福建'), (15, '吉林'), (30, '新疆')], verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.SmallIntegerField(choices=[(2, '保险公司'), (5, '管理员'), (1, '医院'), (4, '医疗设备供应商'), (3, '医药供应商')], max_length=32, verbose_name='用户种类'),
        ),
    ]
