# Generated by Django 4.0.4 on 2022-05-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_drogs_company_evaluate_alter_hospital_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices_company_evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices_company_name', models.CharField(max_length=32, verbose_name='医药公司名称')),
                ('hospital_name', models.CharField(max_length=32, verbose_name='医院名称')),
                ('score', models.IntegerField(verbose_name='评估分数')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.SmallIntegerField(choices=[(22, '山东'), (9, '海南'), (11, '河南'), (20, '宁夏'), (25, '上海'), (18, '辽宁'), (32, '浙江'), (4, '福建'), (24, '陕西'), (27, '台湾'), (16, '江苏'), (34, '澳门'), (23, '山西'), (7, '广西'), (3, '重庆'), (19, '内蒙古'), (17, '江西'), (31, '云南'), (5, '甘肃'), (29, '西藏'), (12, '黑龙江'), (13, '湖北'), (14, '湖南'), (1, '安徽'), (26, '四川'), (6, '广东'), (10, '河北'), (33, '香港'), (21, '青海'), (30, '新疆'), (15, '吉林'), (28, '天津'), (2, '北京'), (8, '贵州')], verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.SmallIntegerField(choices=[(2, '保险公司'), (3, '医药供应商'), (5, '管理员'), (1, '医院'), (4, '医疗设备供应商')], max_length=32, verbose_name='用户种类'),
        ),
    ]
